PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Staff;
DROP TABLE IF EXISTS "Log";
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS "Set";
DROP TABLE IF EXISTS Card;

CREATE TABLE Staff (
  StaffID INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  PhoneNo TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  
  CHECK (Email LIKE '%@%.%'),
  CHECK (PhoneNo LIKE '04%')
);

CREATE TABLE "Log" (
  LogID INTEGER PRIMARY KEY AUTOINCREMENT,
  ChangedByStaffID INTEGER,
  TableName TEXT NOT NULL,
  RecordID TEXT NOT NULL,
  Field TEXT,
  "Action" TEXT NOT NULL,
  OldValue TEXT,
  NewValue TEXT,
  DateChanged TEXT NOT NULL,
  
  FOREIGN KEY (ChangedByStaffID) REFERENCES Staff(StaffID)
);

CREATE TABLE Player (
  PlayerID INTEGER PRIMARY KEY AUTOINCREMENT,
  PlayPokemonID INTEGER NOT NULL UNIQUE,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  PhoneNo TEXT NOT NULL UNIQUE,
  DateJoined TEXT NOT NULL,
  
  CHECK (Email LIKE '%@%.%'),
  CHECK (PhoneNo LIKE '04%')
);

CREATE TABLE "Set" (
  SetID TEXT PRIMARY KEY,
  SetName TEXT NOT NULL,
  SetTotalNo NOT NULL,
  ReleaseDate NOT NULL
);

CREATE TABLE Card (
  CardID INTEGER PRIMARY KEY AUTOINCREMENT,
  SetID TEXT NOT NULL,
  Name TEXT NOT NULL,
  CollectorNo INTEGER NOT NULL,
  Rarity TEXT NOT NULL,
  RegulationMark TEXT NOT NULL,
  
  FOREIGN KEY (SetID) REFERENCES "Set"(SetID)
);