PRAGMA foreign_keys = OFF;

DROP TABLE IF EXISTS "Match";
DROP TABLE IF EXISTS Registration;
DROP TABLE IF EXISTS Tournament;
DROP TABLE IF EXISTS Deck;
DROP TABLE IF EXISTS PokemonCard;
DROP TABLE IF EXISTS Card;
DROP TABLE IF EXISTS "Set";
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS "Log";
DROP TABLE IF EXISTS Staff;

PRAGMA foreign_keys = ON;

CREATE TABLE Staff (
  StaffID INTEGER PRIMARY KEY AUTOINCREMENT,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  PhoneNo TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  
  CHECK (Email LIKE '%@%.%'),
  CHECK (PhoneNo LIKE '04%')
);

CREATE TABLE "Log" (
  LogID INTEGER PRIMARY KEY AUTOINCREMENT,
  ChangedByStaffID INTEGER,
  TableName TEXT NOT NULL,
  RecordID TEXT NOT NULL,
  Field TEXT,
  "Action" TEXT NOT NULL,
  OldValue TEXT,
  NewValue TEXT,
  DateChanged TEXT NOT NULL DEFAULT CURRENT_DATE,
  
  FOREIGN KEY (ChangedByStaffID) REFERENCES Staff(StaffID)
);

CREATE TABLE Player (
  PlayerID INTEGER PRIMARY KEY AUTOINCREMENT,
  PlayPokemonID INTEGER NOT NULL UNIQUE,
  FirstName TEXT NOT NULL,
  LastName TEXT NOT NULL,
  Email TEXT NOT NULL UNIQUE,
  PhoneNo TEXT NOT NULL UNIQUE,
  DateJoined TEXT NOT NULL DEFAULT CURRENT_DATE,
  
  CHECK (Email LIKE '%@%.%'),
  CHECK (PhoneNo LIKE '04%')
);

CREATE TABLE "Set" (
  SetID TEXT PRIMARY KEY,
  SetName TEXT NOT NULL,
  SetTotalNo INTEGER NOT NULL,
  ReleaseDate TEXT NOT NULL
);

CREATE TABLE Card (
  CardID INTEGER PRIMARY KEY AUTOINCREMENT,
  SetID TEXT NOT NULL,
  Name TEXT NOT NULL,
  CollectorNo INTEGER NOT NULL,
  Rarity TEXT NOT NULL,
  RegulationMark TEXT NOT NULL,
  
  FOREIGN KEY (SetID) REFERENCES "Set"(SetID) ON UPDATE CASCADE
);

CREATE TABLE PokemonCard (
  CardID INTEGER PRIMARY KEY,
  HP INTEGER NOT NULL,
  PokemonType TEXT NOT NULL,
  Stage TEXT NOT NULL,

  FOREIGN KEY (CardID) REFERENCES Card(CardID)
);

CREATE TABLE Deck (
  DeckID INTEGER PRIMARY KEY AUTOINCREMENT,
  PlayerID INTEGER NOT NULL,
  CardID INTEGER NOT NULL,
  
  FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID),
  FOREIGN KEY (CardID) REFERENCES Card(CardID)
);

CREATE TABLE Tournament (
  TournamentID INTEGER PRIMARY KEY AUTOINCREMENT,
  TournamentName TEXT NOT NULL,
  "Status" TEXT NOT NULL DEFAULT 'Scheduled',

  CHECK ("Status" IN ('Scheduled', 'Ongoing', 'Completed'))
);

CREATE TABLE Registration (
  RegistrationID INTEGER PRIMARY KEY AUTOINCREMENT,
  TournamentID INTEGER NOT NULL,
  PlayerID INTEGER NOT NULL,
  MatchPoints INTEGER NOT NULL,
  WinPercentage REAL,
  IsInTopCut INTEGER,
  
  FOREIGN KEY (TournamentID) REFERENCES Tournament(TournamentID),
  FOREIGN KEY (PlayerID) REFERENCES Player(PlayerID)
);

CREATE TABLE "Match" (
  MatchID INTEGER PRIMARY KEY AUTOINCREMENT,
  TournamentID INTEGER NOT NULL,
  Player1ID INTEGER NOT NULL,
  Player2ID INTEGER NOT NULL,
  RoundName TEXT NOT NULL,
  P1GamesWon INTEGER NOT NULL,
  P2GamesWon INTEGER NOT NULL,
  MatchStatus TEXT NOT NULL DEFAULT 'Scheduled',
  MatchDate TEXT DEFAULT CURRENT_DATE,
  
  FOREIGN KEY (TournamentID) REFERENCES Tournament(TournamentID),
  FOREIGN KEY (Player1ID) REFERENCES Player(PlayerID),
  FOREIGN KEY (Player2ID) REFERENCES Player(PlayerID)

  CHECK (Player1ID != Player2ID),
  CHECK (MatchStatus IN ('Scheduled', 'Ongoing', 'Completed'))
);